config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.two:
      branch: 450-improve-SQA-rating
      repo: https://bitbucket.org/cessda/cessda.cvs.two
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-harlequin-fowl.sh
        container: qc.acc_zippy-beige-termite
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-burgundy-dachshund.sh
        container: qc.doc_droopy-wisteria-butterfly
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-bistre-mau.sh
        container: qc.doc_paltry-chartreuse-rat
      bitbucket.org/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-charcoal-guppy.sh
        container: qc.doc_zippy-asparagus-bulldog
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-emerald-wolf.sh
        container: qc.lic_wimpy-aquamarine-caracal
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.cvs.two cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-amaranth-flamingo.sh
        container: qc.met_nerdy-alizarin-bison
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-plum-wombat.sh
        container: qc.sty_frumpy-violet-bat
      bitbucket.org/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-xanthic-albatross.sh
        container: qc.sty_scanty-coral-jellyfish
      bitbucket.org/cessda/cessda.cvs.two stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-flax-drever.sh
        container: qc.sty_chummy-cornflower-wombat
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-sangria-caiman.sh
        container: qc.ver_cozy-orange-tzu
timeout: 1800
