config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.two:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.cvs.two
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-aquamarine-serval.sh
        container: qc.acc_silly-champagne-bear
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-wheat-spitz.sh
        container: qc.doc_slaphappy-razzmatazz-fly
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-champagne-cuttlefish.sh
        container: qc.doc_chewy-zucchini-rattlesnake
      bitbucket.org/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-violet-raccoon.sh
        container: qc.doc_whiny-alizarin-wrasse
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-xanthic-hippopotamus.sh
        container: qc.lic_hilly-gold-sheep
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-bistre-greyhound.sh
        container: qc.sty_droopy-malachite-nightingale
      bitbucket.org/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-gamboge-capuchin.sh
        container: qc.sty_smelly-celadon-raccoon
      bitbucket.org/cessda/cessda.cvs.two stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-amethyst-chinook.sh
        container: qc.sty_crabby-black-dragonfly
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-black-terrier.sh
        container: qc.ver_sickly-cinnamon-crab
timeout: 1800
