config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.two:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.cvs.two
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-zucchini-serval.sh
        container: qc.acc_snoopy-champagne-ostrich
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-denim-greyhound.sh
        container: qc.doc_shabby-chestnut-greyhound
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-rose-mayfly.sh
        container: qc.doc_hazy-flax-koala
      bitbucket.org/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-cardinal-hornet.sh
        container: qc.doc_ugly-silver-avocet
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-violet-tuatara.sh
        container: qc.lic_flabby-pink-booby
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.surly-persimmon-spider.sh
        container: qc.sty_sleepy-cobalt-badger
      bitbucket.org/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-chestnut-gharial.sh
        container: qc.sty_cloudy-periwinkle-chamois
      bitbucket.org/cessda/cessda.cvs.two stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-blue-lobster.sh
        container: qc.sty_pretty-purple-neanderthal
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-beige-crocodile.sh
        container: qc.ver_jumpy-sepia-oyster
timeout: 1800
