config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.two:
      branch: 450-improve-SQA-rating
      repo: https://bitbucket.org/cessda/cessda.cvs.two
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-myrtle-hamster.sh
        container: qc.acc_foggy-cinnabar-termite
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-cobalt-wallaby.sh
        container: qc.doc_clammy-emerald-blue
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-sepia-bison.sh
        container: qc.doc_skanky-chartreuse-bonobo
      bitbucket.org/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-periwinkle-binturong.sh
        container: qc.doc_chummy-magenta-owl
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-chartreuse-hamster.sh
        container: qc.lic_cozy-yellow-ant
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.cvs.two cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-khaki-forest.sh
        container: qc.met_pokey-puce-capuchin
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-amaranth-tetra.sh
        container: qc.sty_stuffy-pear-lemming
      bitbucket.org/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-orange-frise.sh
        container: qc.sty_chummy-wisteria-akbash
      bitbucket.org/cessda/cessda.cvs.two stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-cinnabar-spider.sh
        container: qc.sty_hilly-zucchini-dogfish
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-cornflower-flounder.sh
        container: qc.ver_lanky-eggplant-abyssinian
timeout: 1800
