config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.two:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.cvs.two
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-olivine-worm.sh
        container: qc.acc_sleazy-platinum-horse
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-pink-wasp.sh
        container: qc.doc_scanty-scarlet-kakapo
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-coral-zebu.sh
        container: qc.doc_randy-mustard-malamute
      bitbucket.org/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-ruby-drever.sh
        container: qc.doc_sickly-lavender-kudu
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-brass-eleuth.sh
        container: qc.lic_cheeky-orchid-rat
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-taupe-reindeer.sh
        container: qc.sty_beady-seashell-baboon
      bitbucket.org/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-burgundy-chin.sh
        container: qc.sty_sleazy-green-quokka
      bitbucket.org/cessda/cessda.cvs.two stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-jade-gibbon.sh
        container: qc.sty_snazzy-persimmon-chinchilla
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-smalt-tapir.sh
        container: qc.ver_wimpy-orange-gorilla
timeout: 1800
