config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.two:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.cvs.two
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-puce-caracal.sh
        container: qc.acc_lovely-lavender-mist
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-magnolia-uguisu.sh
        container: qc.doc_paltry-puce-ocelot
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-ochre-lemming.sh
        container: qc.doc_queasy-celadon-affenpinscher
      bitbucket.org/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-wisteria-chihuahua.sh
        container: qc.doc_snippy-rose-audemer
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-cobalt-lobster.sh
        container: qc.lic_wimpy-auburn-argentino
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-platinum-impala.sh
        container: qc.sty_bumpy-ivory-mammoth
      bitbucket.org/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-peach-termite.sh
        container: qc.sty_craggy-amber-mule
      bitbucket.org/cessda/cessda.cvs.two stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-teal-mouse.sh
        container: qc.sty_squirrely-ecru-swan
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-russet-loon.sh
        container: qc.ver_cheeky-white-seahorse
timeout: 1800
