config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.two:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.cvs.two
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-white-molly.sh
        container: qc.acc_gloppy-cinnabar-jellyfish
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-heliotrope-zonkey.sh
        container: qc.doc_muggy-alizarin-uakari
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-aqua-booby.sh
        container: qc.doc_shaky-ruby-chihuahua
      bitbucket.org/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-seashell-gecko.sh
        container: qc.doc_ready-cinnabar-affenpinscher
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-turquoise-insect.sh
        container: qc.lic_skinny-maroon-hound
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.surly-amber-neanderthal.sh
        container: qc.sty_lumpy-ruby-gecko
      bitbucket.org/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-pink-cattle.sh
        container: qc.sty_foggy-corn-nightingale
      bitbucket.org/cessda/cessda.cvs.two stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-burgundy-monkey.sh
        container: qc.sty_hasty-cardinal-kangaroo
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-mustard-javanese.sh
        container: qc.ver_leaky-charcoal-clam
timeout: 5400
