config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.two:
      branch: 450-improve-SQA-rating
      repo: https://bitbucket.org/cessda/cessda.cvs.two
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-pink-rattlesnake.sh
        container: qc.acc_cheeky-carmine-chamois
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-charcoal-rottweiler.sh
        container: qc.doc_ready-emerald-cow
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-aquamarine-zebu.sh
        container: qc.doc_wiggy-firebrick-bonobo
      bitbucket.org/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-blue-wolverine.sh
        container: qc.doc_grumpy-violet-barracuda
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-tan-oriole.sh
        container: qc.lic_leaky-red-pig
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.cvs.two cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-ruby-vulture.sh
        container: qc.met_blurry-charcoal-collie
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.messy-periwinkle-dugong.sh
        container: qc.sty_ugly-amaranth-seal
      bitbucket.org/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-khaki-whale.sh
        container: qc.sty_slaphappy-white-monster
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cream-chicken.sh
        container: qc.ver_randy-xanthic-tuatara
timeout: 5400
