config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.two:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.cvs.two
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-harlequin-buffalo.sh
        container: qc.acc_stuffy-ruby-mandrill
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-heliotrope-lizard.sh
        container: qc.doc_greasy-aqua-earwig
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-taupe-crocodile.sh
        container: qc.doc_homely-buff-scorpion
      bitbucket.org/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-cardinal-bandicoot.sh
        container: qc.doc_leaky-cerulean-llama
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-xanthic-moorhen.sh
        container: qc.lic_shaky-aquamarine-dingo
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.randy-platinum-javanese.sh
        container: qc.sty_muzzy-cyan-zonkey
      bitbucket.org/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-lilac-coati.sh
        container: qc.sty_woolly-lemon-catfish
      bitbucket.org/cessda/cessda.cvs.two stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-apricot-lion.sh
        container: qc.sty_snoopy-lavender-earwig
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-bronze-yak.sh
        container: qc.ver_shaky-bronze-dogfish
timeout: 5400
