config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.two:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.cvs.two
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-purple-zorse.sh
        container: qc.acc_surly-peach-caterpillar
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-copper-boar.sh
        container: qc.doc_thirsty-jade-budgerigar
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-purple-dalmatian.sh
        container: qc.doc_nerdy-peach-octopus
      bitbucket.org/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-magenta-angelfish.sh
        container: qc.doc_goopy-cerulean-moose
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-chestnut-caracal.sh
        container: qc.lic_blurry-charcoal-javanese
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-persimmon-lion.sh
        container: qc.sty_tacky-sapphire-moose
      bitbucket.org/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-harlequin-ragdoll.sh
        container: qc.sty_squeaky-chestnut-magpie
      bitbucket.org/cessda/cessda.cvs.two stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-linen-guppy.sh
        container: qc.sty_jumpy-cardinal-warthog
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-grey-badger.sh
        container: qc.ver_crabby-turquoise-spitz
timeout: 1800
