config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.two:
      branch: 450-improve-SQA-rating
      repo: https://bitbucket.org/cessda/cessda.cvs.two
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-zucchini-dunker.sh
        container: qc.acc_baggy-malachite-eel
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-cornflower-orangutan.sh
        container: qc.doc_queasy-saffron-starfish
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-persimmon-pig.sh
        container: qc.doc_lousy-pear-slug
      bitbucket.org/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-brass-cougar.sh
        container: qc.doc_cozy-aqua-audemer
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-sapphire-tiger.sh
        container: qc.lic_slimy-smalt-squirrel
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.cvs.two cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-orchid-goose.sh
        container: qc.met_randy-bronze-monster
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.homely-cornflower-impala.sh
        container: qc.sty_shaggy-cerulean-maltese
      bitbucket.org/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-amaranth-caracal.sh
        container: qc.sty_homey-razzmatazz-bear
      bitbucket.org/cessda/cessda.cvs.two stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-eggplant-mole.sh
        container: qc.sty_hasty-aqua-burmese
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-ivory-walrus.sh
        container: qc.ver_muzzy-aquamarine-antelope
timeout: 1800
