config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.two:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.cvs.two
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-olivine-whippet.sh
        container: qc.acc_sleazy-plum-cow
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-malachite-anteater.sh
        container: qc.doc_lousy-olive-abyssinian
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-purple-giraffe.sh
        container: qc.doc_snoopy-cerulean-mole
      bitbucket.org/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-grey-wasp.sh
        container: qc.doc_clammy-ruby-bulldog
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-tomato-spitz.sh
        container: qc.lic_frumpy-saffron-beaver
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-amber-hyrax.sh
        container: qc.sty_gimpy-grey-kingfisher
      bitbucket.org/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-gamboge-booby.sh
        container: qc.sty_fuzzy-khaki-cat
      bitbucket.org/cessda/cessda.cvs.two stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-taupe-shrimp.sh
        container: qc.sty_beady-champagne-crocodile
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-razzmatazz-uakari.sh
        container: qc.ver_bumpy-auburn-panda
timeout: 1800
